version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS 
  pre_build:
    commands:
      - $REPO_URL
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URL
      - docker login --username AWS --password $AWS_LOGIN_PASSWORD $REPO_URL
      - # Replace text in files (requires custom solution)
      - $COMMIT_HASH = $CODEBUILD_RESOLVED_SOURCE_VERSION.substring(0,7)
      - if ($COMMIT_HASH -eq $null) { $COMMIT_HASH = "latest" }
      - $IMAGE_TAG = $COMMIT_HASH
  build:
    commands:
      - # Build the main container
      - docker build -t $REPO_URL $FOLDER_PATH
      - # Build the echo-service container
      - cd echo-service
      - aws codebuild build --project-name echo-service --source-version $CODEBUILD_RESOLVED_SOURCE_VERSION
      - cd ..
  post_build:
    commands:
      - # Push the main container
      - docker tag $REPO_URL $REPO_URL:$IMAGE_TAG
      - docker push $REPO_URL:$IMAGE_TAG
      - # Push the echo-service container
      - docker tag $REPO_URL-echo-service $REPO_URL-echo-service:$IMAGE_TAG
      - docker push $REPO_URL-echo-service:$IMAGE_TAG
      - # Update task definition (requires custom solution)
      - New-Item -ItemType Directory -Path artifacts -Force
      - Copy-Item tmp-ntd.json artifacts\task-definition.json

artifacts:
  files:
    - '**/*'
  base-directory: 'artifacts'
  discard-paths: yes