version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 240484791744.dkr.ecr.eu-west-1.amazonaws.com
      - # Replace text in files (requires custom solution)
      - COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - if [ -z "$COMMIT_HASH" ]; then COMMIT_HASH="latest"; fi
      - IMAGE_TAG=$COMMIT_HASH
      - ls
      - ls $FOLDER_PATH
  build:
    commands:
      - # Build the main container
      - echo Build started on `date`
      - docker build -t $REPO_URL $FOLDER_PATH
      - # Build the echo-service container
  post_build:
    commands:
      - # Push the main container
      # First run - docker push $REPO_URL || true
      - docker tag $REPO_URL $REPO_URL:$IMAGE_TAG
      - docker push $REPO_URL:$IMAGE_TAG
      - # Push the echo-service container
      - docker tag $REPO_URL $REPO_URL:$IMAGE_TAG
      - docker push $REPO_URL:$IMAGE_TAG
      - echo Updating the Amazon ECS task definition...
      - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $TASK_DEFINITION_FAMILY --query '{
          containerDefinitions: taskDefinition.containerDefinitions,
          family: taskDefinition.family,
          taskRoleArn: taskDefinition.taskRoleArn,
          executionRoleArn: taskDefinition.executionRoleArn,
          networkMode: taskDefinition.networkMode,
          volumes: taskDefinition.volumes,
          placementConstraints: taskDefinition.placementConstraints,
          requiresCompatibilities: taskDefinition.requiresCompatibilities,
          cpu: taskDefinition.cpu,
          memory: taskDefinition.memory
      }' | tee tmp-td.json)
      - sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" tmp-td.json
      - sed -i "s|REPO_URL|$REPO_URL|g" tmp-td.json
      - aws ecs register-task-definition --cli-input-json file://tmp-td.json
  artifacts:
    base-directory: echo-service/bin/Debug/net5.0
    files:
      - echo-service.dll
    discard-paths: yes

artifacts:
  files:
    - '**/*'
  base-directory: 'artifacts'
  discard-paths: yes